wandb:
  entity: prj-research
  project: sequence-transformer
  group: pretraining
  name: they-come-from-uranus # can name wandb run
dataset:
  ctrl_file: '/Users/chasewesthoff/Desktop/PJR/drill/Preprocessing/key_train.csv'
  data_dir: '/Users/chasewesthoff/Desktop/PJR/drill/Preprocessing/Segments'
  rand_chunk_prob: 0.0
optimization:
  n_epochs: 5
  lr: 1e-4
  batch_size: 4